//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrittersWeb.Controllers.Assets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticHtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrittersWeb.Controllers.Assets.StaticHtml", typeof(StaticHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin: 0px; height: 100vh; font-family: arial; font-size: 18px;&quot;&gt;
        ///    &lt;script&gt;
        ///        function sendPassword() {            
        ///            let password = document.getElementById(&quot;password&quot;).value;
        ///            let xhr = new XMLHttpRequest();
        ///            xhr.open(&quot;POST&quot;, &quot;/account/setpassword/&quot;);
        ///            xhr.setRequestHeader(&quot;Accept&quot;, &quot;application/json&quot;);
        ///            xhr.setRequestHeader(&quot;Conten [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangePassword_html {
            get {
                return ResourceManager.GetString("ChangePassword_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;margin: 0px; height: 100vh; font-family: arial&quot;&gt;
        ///    &lt;div style=&quot;background: rgb(79, 90, 110); width: 100%; height: 100%;&quot;&gt;
        ///        &lt;div style=&quot;border: solid darkgray; width: 500px; height: 300px; color: white; position: absolute; top: 50%; right: 50%; transform: translate(50%, -50%); 
        ///             padding: 0px; font-size: 20px; display: flex; flex-direction: column; align-items: center; justify-cont [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailConfirmed_html {
            get {
                return ResourceManager.GetString("MailConfirmed_html", resourceCulture);
            }
        }
    }
}
